### PR TITLE
add -trimprefix and -autotrimprefix

### PR DESCRIPTION
**Pull request by wttw**
This adds -trimprefix and -autotrimprefix functionality, as suggested upstream in https://github.com/golang/go/issues/16539

Given an enum that uses a prefix to ensure the names are unique this allows stripping that prefix from the generated strings. {FooBar, FooBaz, FooQux} will map onto {"Bar", "Baz", "Qux"} if run with -trimprefix=Foo or with -autotrimprefix.

It can also be combined with the -transform flag to convert FooBarBaz to "bar-baz" or "bar_baz".

### CODE REVIEW

**Comment by itsjamie** [comment]
This would solve issue #18.

**Comment by tonyhb** [comment]
yesss

**Comment by weirdgiraffe** [comment]
:+1:  `-autotrimprefix` is great if you want to genererate multiple enums

**Comment by alvaroloes** [comment]
@wttw Thanks you very much for this!
I like your contribution and the code a lot. After giving this some thought, I think the `trimprefix` would be a very good addition, but I'm not so happy with the `autotrimprefix` flag. In my experience, being implicit often leads to confusion. Especially in situations like this, where we are "giving" names to constants. It is best to be explicit and know in every moment how we are transforming the names to avoid surprises.

I would we more than happy to accept and merge this but without the autotrim. What do you think about removing the "autotrimprefix" code from this branch so that I can merge the PR? I would _really_ appreciate it.

**Comment by wttw** [comment]
Sure. I'll redo that against HEAD in the next day or two.

**Comment by wttw** [comment]
Ready to merge. (Also fixes the broken tests).

**Comment by alvaroloes** [comment]
Thank you very much!

**Pull request merged**
